### ISSUE TITLE
Possible alternatives using source data

### ISSUE THREAD

**Issue by jpmckinney** [leonL/ontario-postal-code-concordance#1]
You can use the province's [shapefile](http://www.elections.on.ca/en/voting-in-ontario/electoral-districts/electoral-districts--maps--shapefiles-and-street-index-guide.html) and [free data](geocoder.ca/?freedata=1) from Geocoder.ca to get the results you want.

(I'll be at CivicTechTO this Tuesday if you want to discuss!)

**Comment by leonL** [comment]
Thanks James. I'm done building the Ontario concordance, but I was just about to build one for Manitoba and Saskatchewan postal codes. I'd be happy to chat about alternative ways of doing it, and it will be nice to meet you besides... see you Tuesday.

**Comment by jpmckinney** [comment]
https://github.com/opennorth/represent-canada-data/

**Comment by leonL** [comment]
Thanks again for the chat last week James. I went to the represent data page to get those concordances this morning, but couldn't quite figure it out. Sorry if I'm being slow on the uptake. For one the current state of the repo seems quite different than the one you showed me. I find if I need to roll it back to a commit from sometime last year to see those folders for each province at the root. Nonetheless, even when I do that I only see shape files in them, not pcode or riding data. 

I should have paid closer attention when you were showing my the repo ... I just assumed it would be simple to find the data once I had the link. Anyway, I've started my script to fetch the data from the API, but if you have a moment to clear up my confusion I'd be grateful. 

Thanks.

PS: In case you're still in Toronto this week, CanadaLand is hosting an interesting looking event tomorrow night: https://www.facebook.com/events/744584722342949/

**Comment by jpmckinney** [comment]
The province shapefiles are here (scroll all the way down): https://github.com/opennorth/represent-canada-data/tree/master/boundaries/ocd-division/country:ca

If you load each province into a PostGIS database, as well as postcode data from for example [GeoCoder.ca](http://geocoder.ca/?freedata=1), then you can perform much faster geospatial queries to create your own concordances.

**Comment by leonL** [comment]
Gottcha. I did misunderstand. I thought that after we discussed the PostGIS solution, you were also saying that the concordance was available in the repo (not just the shapefiles). Of course now that I think about it why would you have even told me about the PostGIS solution if the concordance was already there to be downloaded. :$

Although the PostGIS method is quicker, I'm gonna use the API this time around. The script for fetching the data is ready to go, and in terms of labour hours its the simpler one for me at this point. But it's great to know of the other option in case I need it down the road. Thanks again for the suggestion.

**Comment by jpmckinney** [comment]
If more people use the API to query every possible postal code, we'll eventually start blocking this really obvious scripts, so letting you know that there is a better solution :)

**Comment by leonL** [comment]
Got it. I'll take that into consideration in the future.
